############################
# Coder : Mr.Tr3v!0n       #
# Hanya seorang nooby 😢.  #
# Di Buat : 19, jan 2019   #
# jam : [13]:[25].         #
# Team : Black Coder Crush #
# Slam Anak Bangsa.        #
############################
z="
";rBz='p2} ';OCz='   "';lCz='sh g';bz='[40;';uBz='oder';PBz='}║ "';VCz=' ╚══';ACz='b}║ ';Lz='33;1';az='hi="';mBz=' ${b';Mz='b="\';MBz='8387';cz='clea';NBz='9017';eBz='  ✬$';VBz='m}  ';OBz='166 ';KBz='a: $';qBz='{b}"';iBz='  ║ ';xBz='G I ';Zz='[39;';yBz='N ${';Qz='pu="';kz='║ ${';WCz='═╝ "';LBz='{b}0';yz='    ';IBz='Kont';nBz='} "';gCz='} Lo';iz='════';SCz='${h}';qz='User';Cz='29;1';sBz=' Bla';dBz='{m} ';vz=' ${k';Hz='31;1';ABz='${p2';TCz='√Suc';tBz='ck C';nCz='onge';wBz='L O ';TBz=' ✬  ';UBz='}✬${';rz='name';KCz='Pass';Yz='p2="';hBz='{c}✬';pz='${b}';UCz='ces"';GBz='   $';Rz='\033';bCz='p 1';LCz='p2}"';PCz='║ Us';RBz='╝"';FBz='dmin';oz='Tau ';fCz=']${h';iCz='Succ';Uz='p1="';BBz='} Bi';FCz='Crus';oCz='rsv1';NCz='╗   ';jz='╗"';JCz='ser&';gz='k}  ';CBz='sa C';XCz='║ Pa';vBz='}║ $';JBz='ak W';ICz='{k}U';lBz='${c}';jCz='ess.';Fz='30;1';ZBz='{b} ';MCz=' "  ';cCz='p}[$';kCz='."';WBz=' ✬${';hz='╔═══';Wz='m1="';tz='word';aBz='  ✬ ';kBz='✬   ';bBz='  ${';pBz='}   ';xz='║   ';BCz=' ${p';Bz='033[';QCz='erna';Nz='34;1';Iz='h="\';wz='}║"';DBz='hat ';Az='p="\';EBz='Wa A';Tz='1m"';CCz='2}OF';HBz='{p2}';Kz='k="\';ZCz='d:  ';Xz='[38;';Vz='[37;';HCz=' ║ $';eCz='${p}';ECz='AL "';DCz='FICI';Sz='[36;';dCz='{k}+';fBz='"';nz='Gak ';jBz='  ║$';QBz='╚═══';YCz='swor';ez='echo';pCz='.sh';mCz='eret';RCz='me: ';gBz='   ✬';Pz='35;1';Oz='c="\';SBz='b}  ';Gz='m="\';Jz='32;1';mz='ika ';aCz='slee';uz=' nya';hCz='gin ';oBz='╗${k';Dz='m"';fz=' "${';Ez='a="\';GCz='h ${';cBz='k}✬$';XBz='  ╔═';sz='&Pas';YBz='══╗$';lz='p2}J';dz='r';
eval "$Az$Bz$Cz$Dz$z$Ez$Bz$Fz$Dz$z$Gz$Bz$Hz$Dz$z$Iz$Bz$Jz$Dz$z$Kz$Bz$Lz$Dz$z$Mz$Bz$Nz$Dz$z$Oz$Bz$Pz$Dz$z$Qz$Rz$Sz$Tz$z$Uz$Rz$Vz$Tz$z$Wz$Rz$Xz$Tz$z$Yz$Rz$Zz$Tz$z$az$Rz$bz$Tz$z$cz$dz$z$ez$fz$gz$hz$iz$iz$iz$iz$iz$iz$iz$iz$jz$z$ez$fz$gz$kz$lz$mz$nz$oz$pz$qz$rz$sz$tz$uz$vz$wz$z$ez$fz$gz$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$yz$yz$vz$wz$z$ez$fz$gz$xz$GBz$HBz$IBz$JBz$KBz$LBz$MBz$NBz$OBz$yz$vz$PBz$z$ez$fz$gz$QBz$iz$iz$iz$iz$iz$iz$iz$iz$RBz$z$ez$z$ez$fz$SBz$TBz$vz$UBz$VBz$WBz$SBz$XBz$iz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$ZBz$fBz$z$ez$fz$VBz$gBz$GBz$hBz$yz$pz$iBz$yz$jBz$dBz$yz$kBz$lBz$kBz$mBz$nBz$z$ez$fz$gz$yz$WBz$SBz$yz$hz$iz$iz$oBz$pBz$eBz$qBz$z$ez$fz$rBz$sBz$tBz$uBz$mBz$vBz$HBz$wBz$xBz$yBz$ACz$BCz$CCz$DCz$ECz$z$ez$fz$rBz$yz$FCz$GCz$SBz$HCz$ICz$JCz$KCz$mBz$PBz$z$ez$fz$SBz$yz$yz$yz$QBz$iz$iz$RBz$z$ez$fz$LCz$z$ez$MCz$yz$hz$iz$iz$NCz$OCz$z$ez$MCz$yz$PCz$QCz$RCz$SCz$TCz$UCz$z$ez$fz$rBz$yz$VCz$iz$iz$WCz$z$ez$MCz$yz$yz$yz$yz$hz$iz$iz$NCz$OCz$z$ez$MCz$yz$yz$yz$yz$XCz$YCz$ZCz$SCz$TCz$UCz$z$ez$fz$rBz$yz$yz$yz$yz$VCz$iz$iz$WCz$z$aCz$bCz$z$ez$fz$cCz$dCz$eCz$fCz$gCz$hCz$iCz$jCz$kCz$z$aCz$bCz$z$lCz$mCz$nCz$oCz$pCz" 