############################
# Coder : Mr.Tr3v!0n       #
# Hanya seorang nooby 😢.  #
# Di Buat : 19, jan 2019   #
# jam : [13]:[25].         #
# Team : Black Coder Crush #
# Slam Anak Bangsa.        #
############################
z="
";Wz='p2="';XCz=' ];t';mz='Tau ';Xz='[39;';Az='a="\';gz='════';Bz='033[';IBz='a: $';eCz='else';rBz='ck C';bCz='sh p';Hz='32;1';kBz=' ${b';fBz='{c}✬';FCz=' ║ $';oBz='{b}"';sz=' nya';bz='r';GCz='{k}U';cz='echo';Dz='m"';yz='} Bi';HBz='ak W';RBz=' ✬  ';iBz='✬   ';OCz='   ║';XBz='{b} ';rz='word';OBz='╚═══';hBz='  ║$';FBz='{p2}';lz='Gak ';WBz='══╗$';JCz=' ╔══';mBz='╗${k';Oz='pu="';wBz='N ${';ACz='2}OF';vz='║   ';ez='k}  ';Ez='m="\';az='clea';Mz='c="\';jz='p2}J';xz='${p2';qz='&Pas';Fz='31;1';ZCz=' ╚══';BCz='FICI';YBz='  ✬ ';xBz='b}║ ';EBz='   $';QBz='b}  ';oz='User';NCz='"   ';uz='}║"';YCz='hen';HCz='ser&';tz=' ${k';hCz='!!"';Tz='[37;';cCz='ass.';kz='ika ';Lz='34;1';dz=' "${';ABz='sa C';pBz='p2} ';CBz='Wa A';MBz='166 ';BBz='hat ';kCz='sh u';DCz='Crus';GBz='Kont';RCz='e: "';eBz='   ✬';Cz='30;1';ZBz='  ${';nBz='}   ';fCz='   F';nCz='fi';lBz='} "';dBz='"';Zz='[40;';PBz='╝"';Iz='k="\';Nz='35;1';VBz='  ╔═';fz='╔═══';Uz='m1="';PCz=' Use';WCz='Anak';JBz='{b}0';gCz='iled';SBz='}✬${';Qz='[36;';Jz='33;1';LCz='read';nz='${b}';NBz='}║ "';Sz='p1="';Yz='hi="';gBz='  ║ ';Vz='[38;';QCz='rnam';yBz=' ${p';CCz='AL "';UBz=' ✬${';VCz='s = ';Rz='1m"';cBz='  ✬$';pz='name';Pz='\033';MCz=' -p ';jCz='p 1';Gz='h="\';uBz='L O ';hz='╗"';sBz='oder';iz='║ ${';Kz='b="\';TBz='m}  ';aCz='═╝ "';wz='    ';KBz='8387';LBz='9017';bBz='{m} ';SCz=' rus';tBz='}║ $';dCz='sh';aBz='k}✬$';vBz='G I ';ICz='Pass';UCz=' $ru';DBz='dmin';KCz='═╗"';jBz='${c}';lCz='sr.s';TCz='if [';qBz=' Bla';ECz='h ${';mCz='h';iCz='slee';
eval "$Az$Bz$Cz$Dz$z$Ez$Bz$Fz$Dz$z$Gz$Bz$Hz$Dz$z$Iz$Bz$Jz$Dz$z$Kz$Bz$Lz$Dz$z$Mz$Bz$Nz$Dz$z$Oz$Pz$Qz$Rz$z$Sz$Pz$Tz$Rz$z$Uz$Pz$Vz$Rz$z$Wz$Pz$Xz$Rz$z$Yz$Pz$Zz$Rz$z$az$bz$z$cz$dz$ez$fz$gz$gz$gz$gz$gz$gz$gz$gz$hz$z$cz$dz$ez$iz$jz$kz$lz$mz$nz$oz$pz$qz$rz$sz$tz$uz$z$cz$dz$ez$vz$wz$xz$yz$ABz$BBz$CBz$DBz$wz$wz$tz$uz$z$cz$dz$ez$vz$EBz$FBz$GBz$HBz$IBz$JBz$KBz$LBz$MBz$wz$tz$NBz$z$cz$dz$ez$OBz$gz$gz$gz$gz$gz$gz$gz$gz$PBz$z$cz$z$cz$dz$QBz$RBz$tz$SBz$TBz$UBz$QBz$VBz$gz$WBz$XBz$YBz$ZBz$aBz$bBz$cBz$XBz$dBz$z$cz$dz$TBz$eBz$EBz$fBz$wz$nz$gBz$wz$hBz$bBz$wz$iBz$jBz$iBz$kBz$lBz$z$cz$dz$ez$wz$UBz$QBz$wz$fz$gz$gz$mBz$nBz$cBz$oBz$z$cz$dz$pBz$qBz$rBz$sBz$kBz$tBz$FBz$uBz$vBz$wBz$xBz$yBz$ACz$BCz$CCz$z$cz$dz$pBz$wz$DCz$ECz$QBz$FCz$GCz$HCz$ICz$kBz$NBz$z$cz$dz$QBz$wz$wz$wz$OBz$gz$gz$PBz$z$cz$z$cz$dz$pBz$wz$JCz$gz$gz$KCz$z$LCz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$z$TCz$UCz$VCz$WCz$XCz$YCz$z$cz$dz$pBz$wz$ZCz$gz$gz$aCz$z$bCz$cCz$dCz$z$eCz$z$cz$dz$TBz$wz$fCz$gCz$hCz$z$iCz$jCz$z$kCz$lCz$mCz$z$nCz" 
