############################
# Coder : Mr.Tr3v!0n       #
# Hanya seorang nooby 😢.  #
# Di Buat : 19, jan 2019   #
# jam : [13]:[25].         #
# Team : Black Coder Crush #
# Slam Anak Bangsa.        #
############################
z="
";wCz='p 1';TBz=' ✬  ';QBz='╚═══';RCz='me: ';tCz='File';MCz=' "  ';yBz='N ${';xz='║   ';uz=' nya';ZCz='read';qBz='{b}"';dz='r';sCz='else';Rz='\033';KCz='Pass';PCz='║ Us';Hz='31;1';cCz='║ Pa';ez='echo';Xz='[38;';hCz='if [';qCz='sil.';jBz='  ║$';tz='word';QCz='erna';TCz='√Suc';bBz='  ${';JCz='ser&';Bz='033[';lBz='${c}';Nz='34;1';iBz='  ║ ';BCz=' ${p';IBz='Kont';Dz='m"';DBz='hat ';Iz='h="\';jz='╗"';nCz='en';HCz=' ║ $';SBz='b}  ';NCz='╗   ';UCz='ces"';nBz='} "';ZBz='{b} ';iz='════';Uz='p1="';Qz='pu="';ECz='AL "';XCz=' ╔══';FCz='Crus';fBz='"';rz='name';kCz=' Ban';WCz='═╝ "';yz='    ';uBz='oder';ICz='{k}U';GBz='   $';CBz='sa C';az='hi="';Oz='c="\';gCz='s';NBz='9017';Sz='[36;';aCz=' -p ';oCz='sh b';VCz=' ╚══';gz='k}  ';OCz='   "';eCz='d: "';qz='User';Vz='[37;';Gz='m="\';aBz='  ✬ ';vz=' ${k';dBz='{m} ';mz='ika ';oBz='╗${k';UBz='}✬${';sBz=' Bla';ADz='fi';hz='╔═══';JBz='ak W';Mz='b="\';nz='Gak ';Fz='30;1';Az='p="\';lz='p2}J';SCz='${h}';mCz='];th';Ez='a="\';ABz='${p2';Yz='p2="';cBz='k}✬$';iCz=' $pa';GCz='h ${';Tz='1m"';LBz='{b}0';xCz='sh p';pCz='erha';mBz=' ${b';eBz='  ✬$';YCz='═╗  ';kBz='✬   ';lCz='gsa ';sz='&Pas';jCz='ss =';KBz='a: $';fz=' "${';pz='${b}';Kz='k="\';rCz='sh';ACz='b}║ ';xBz='G I ';EBz='Wa A';XBz='  ╔═';fCz=' pas';cz='clea';wBz='L O ';HBz='{p2}';pBz='}   ';hBz='{c}✬';wz='}║"';WBz=' ✬${';PBz='}║ "';yCz='ass.';Lz='33;1';MBz='8387';LCz='p2}"';DCz='FICI';FBz='dmin';vCz='slee';gBz='   ✬';OBz='166 ';BBz='} Bi';Pz='35;1';Zz='[39;';rBz='p2} ';oz='Tau ';Jz='32;1';Cz='29;1';vBz='}║ $';kz='║ ${';dCz='swor';CCz='2}OF';RBz='╝"';Wz='m1="';uCz='d!!"';bz='[40;';tBz='ck C';VBz='m}  ';bCz='"   ';YBz='══╗$';
eval "$Az$Bz$Cz$Dz$z$Ez$Bz$Fz$Dz$z$Gz$Bz$Hz$Dz$z$Iz$Bz$Jz$Dz$z$Kz$Bz$Lz$Dz$z$Mz$Bz$Nz$Dz$z$Oz$Bz$Pz$Dz$z$Qz$Rz$Sz$Tz$z$Uz$Rz$Vz$Tz$z$Wz$Rz$Xz$Tz$z$Yz$Rz$Zz$Tz$z$az$Rz$bz$Tz$z$cz$dz$z$ez$fz$gz$hz$iz$iz$iz$iz$iz$iz$iz$iz$jz$z$ez$fz$gz$kz$lz$mz$nz$oz$pz$qz$rz$sz$tz$uz$vz$wz$z$ez$fz$gz$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$yz$yz$vz$wz$z$ez$fz$gz$xz$GBz$HBz$IBz$JBz$KBz$LBz$MBz$NBz$OBz$yz$vz$PBz$z$ez$fz$gz$QBz$iz$iz$iz$iz$iz$iz$iz$iz$RBz$z$ez$z$ez$fz$SBz$TBz$vz$UBz$VBz$WBz$SBz$XBz$iz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$ZBz$fBz$z$ez$fz$VBz$gBz$GBz$hBz$yz$pz$iBz$yz$jBz$dBz$yz$kBz$lBz$kBz$mBz$nBz$z$ez$fz$gz$yz$WBz$SBz$yz$hz$iz$iz$oBz$pBz$eBz$qBz$z$ez$fz$rBz$sBz$tBz$uBz$mBz$vBz$HBz$wBz$xBz$yBz$ACz$BCz$CCz$DCz$ECz$z$ez$fz$rBz$yz$FCz$GCz$SBz$HCz$ICz$JCz$KCz$mBz$PBz$z$ez$fz$SBz$yz$yz$yz$QBz$iz$iz$RBz$z$ez$fz$LCz$z$ez$MCz$yz$hz$iz$iz$NCz$OCz$z$ez$MCz$yz$PCz$QCz$RCz$SCz$TCz$UCz$z$ez$fz$rBz$yz$VCz$iz$iz$WCz$z$ez$MCz$yz$yz$yz$yz$XCz$iz$iz$YCz$yz$fBz$z$ZCz$aCz$bCz$yz$yz$yz$yz$cCz$dCz$eCz$fCz$gCz$z$hCz$iCz$jCz$kCz$lCz$mCz$nCz$z$ez$fz$rBz$yz$yz$yz$yz$VCz$iz$iz$WCz$z$oCz$pCz$qCz$rCz$z$sCz$z$ez$fz$VBz$yz$yz$yz$yz$yz$tCz$uCz$z$ez$fz$LCz$z$vCz$wCz$z$cz$dz$z$xCz$yCz$rCz$z$ADz" 