############################
# Coder : Mr.Tr3v!0n       #
# Hanya seorang nooby 😢.  #
# Di Buat : 19, jan 2019   #
# jam : [13]:[25].         #
# Team : Black Coder Crush #
# Slam Anak Bangsa.        #
############################
z="
";uz=' nya';VCz='if [';Mz='b="\';RBz='╝"';Lz='33;1';Iz='h="\';DCz='FICI';lCz='p 1';oz='Tau ';HBz='{p2}';EBz='Wa A';KBz='a: $';iBz='  ║ ';az='hi="';Oz='c="\';Ez='a="\';LCz=' ╔══';Tz='1m"';ZCz=' ];t';Kz='k="\';dBz='{m} ';XBz='  ╔═';Uz='p1="';YCz='Anak';VBz='m}  ';kCz='slee';aBz='  ✬ ';lz='p2}J';dCz='sh p';jBz='  ║$';bz='[40;';iCz='iled';jz='╗"';Bz='033[';MCz='═╗"';NBz='9017';IBz='Kont';XCz='s = ';GBz='   $';bBz='  ${';JCz='ser&';Jz='32;1';LBz='{b}0';rz='name';Yz='p2="';ECz='AL "';ICz='{k}U';rBz='p2} ';UBz='}✬${';FCz='Crus';Dz='m"';MBz='8387';qBz='{b}"';fBz='"';xz='║   ';cz='clea';PBz='}║ "';wz='}║"';WBz=' ✬${';eBz='  ✬$';SBz='b}  ';dz='r';Cz='29;1';YBz='══╗$';KCz='Pass';pBz='}   ';nz='Gak ';vBz='}║ $';yBz='N ${';aCz='hen';Qz='pu="';QBz='╚═══';sz='&Pas';Rz='\033';HCz=' ║ $';vz=' ${k';uBz='oder';FBz='dmin';fz=' "${';mCz='sh g';Xz='[38;';hCz='   F';iz='════';gz='k}  ';NCz='read';CCz='2}OF';TCz='e: "';hz='╔═══';bCz=' ╚══';jCz='!!"';BCz=' ${p';Sz='[36;';Nz='34;1';mz='ika ';pz='${b}';GCz='h ${';ez='echo';Gz='m="\';kBz='✬   ';rCz='fi';nBz='} "';oCz='onge';cBz='k}✬$';UCz=' rus';nCz='eret';xBz='G I ';hBz='{c}✬';gBz='   ✬';sBz=' Bla';gCz='else';Wz='m1="';SCz='rnam';BBz='} Bi';ABz='${p2';qz='User';ACz='b}║ ';Zz='[39;';Az='p="\';oBz='╗${k';OCz=' -p ';Pz='35;1';cCz='═╝ "';CBz='sa C';RCz=' Use';mBz=' ${b';ZBz='{b} ';JBz='ak W';DBz='hat ';tz='word';yz='    ';Vz='[37;';lBz='${c}';eCz='ass.';tBz='ck C';pCz='rs.s';qCz='h';kz='║ ${';OBz='166 ';fCz='sh';wBz='L O ';Fz='30;1';Hz='31;1';TBz=' ✬  ';WCz=' $ru';QCz='   ║';PCz='"   ';
eval "$Az$Bz$Cz$Dz$z$Ez$Bz$Fz$Dz$z$Gz$Bz$Hz$Dz$z$Iz$Bz$Jz$Dz$z$Kz$Bz$Lz$Dz$z$Mz$Bz$Nz$Dz$z$Oz$Bz$Pz$Dz$z$Qz$Rz$Sz$Tz$z$Uz$Rz$Vz$Tz$z$Wz$Rz$Xz$Tz$z$Yz$Rz$Zz$Tz$z$az$Rz$bz$Tz$z$cz$dz$z$ez$fz$gz$hz$iz$iz$iz$iz$iz$iz$iz$iz$jz$z$ez$fz$gz$kz$lz$mz$nz$oz$pz$qz$rz$sz$tz$uz$vz$wz$z$ez$fz$gz$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$yz$yz$vz$wz$z$ez$fz$gz$xz$GBz$HBz$IBz$JBz$KBz$LBz$MBz$NBz$OBz$yz$vz$PBz$z$ez$fz$gz$QBz$iz$iz$iz$iz$iz$iz$iz$iz$RBz$z$ez$z$ez$fz$SBz$TBz$vz$UBz$VBz$WBz$SBz$XBz$iz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$ZBz$fBz$z$ez$fz$VBz$gBz$GBz$hBz$yz$pz$iBz$yz$jBz$dBz$yz$kBz$lBz$kBz$mBz$nBz$z$ez$fz$gz$yz$WBz$SBz$yz$hz$iz$iz$oBz$pBz$eBz$qBz$z$ez$fz$rBz$sBz$tBz$uBz$mBz$vBz$HBz$wBz$xBz$yBz$ACz$BCz$CCz$DCz$ECz$z$ez$fz$rBz$yz$FCz$GCz$SBz$HCz$ICz$JCz$KCz$mBz$PBz$z$ez$fz$SBz$yz$yz$yz$QBz$iz$iz$RBz$z$ez$z$ez$fz$rBz$yz$LCz$iz$iz$MCz$z$NCz$OCz$PCz$QCz$RCz$SCz$TCz$UCz$z$VCz$WCz$XCz$YCz$ZCz$aCz$z$ez$fz$rBz$yz$bCz$iz$iz$cCz$z$dCz$eCz$fCz$z$gCz$z$ez$fz$VBz$yz$hCz$iCz$jCz$z$kCz$lCz$z$mCz$nCz$oCz$pCz$qCz$z$rCz" 
